Part 1: Data Cleaning

In [1]:
# import libraries
import pandas as pd

In [2]:
df = pd.read_excel("ramen_rating_2023.xlsx")
df

,Review #,Brand,Variety,Style,Country,Stars,T
0,4650,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5,NaN
1,4649,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5,NaN
2,4648,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5,NaN
3,4647,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5,NaN
4,4646,Samyang Foods,Samyand Ramen,Pack,United States,5,NaN
...,...,...,...,...,...,...,...
4645,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
4646,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
4647,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
4648,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
4649,1,Westbrae,Miso Ramen,Pack,United States,0.5,NaN

In [3]:
#check null and clean null dataset
df.isnull().sum()

Review #       0
Brand          0
Variety        0
Style          0
Country        0
Stars          2
T           4650
dtype: int64

In [4]:
df = df.dropna(subset=['Stars'])
df

,Review #,Brand,Variety,Style,Country,Stars,T
0,4650,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5,NaN
1,4649,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5,NaN
2,4648,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5,NaN
3,4647,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5,NaN
4,4646,Samyang Foods,Samyand Ramen,Pack,United States,5,NaN
...,...,...,...,...,...,...,...
4645,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
4646,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
4647,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
4648,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
4649,1,Westbrae,Miso Ramen,Pack,United States,0.5,NaN

In [5]:
#drop columns not need
df = df.drop(['Review #', 'T'], axis=1)

In [6]:
df.isnull().sum()

Brand      0
Variety    0
Style      0
Country    0
Stars      0
dtype: int64

In [7]:
df

,Brand,Variety,Style,Country,Stars
0,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5
1,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5
2,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5
3,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5
4,Samyang Foods,Samyand Ramen,Pack,United States,5
...,...,...,...,...,...
4645,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
4646,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1
4647,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2
4648,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2
4649,Westbrae,Miso Ramen,Pack,United States,0.5

In [8]:
df.dtypes

Brand      object
Variety    object
Style      object
Country    object
Stars      object
dtype: object

In [9]:
#clean column Star
df['Stars'].value_counts()

Stars
5                                         938
3.5                                       678
3.75                                      643
4                                         541
4.5                                       315
3.25                                      250
4.25                                      240
3                                         208
2                                         124
2.75                                      124
2.5                                       117
4.75                                      113
1.5                                        64
0                                          61
1                                          53
1.75                                       35
2.25                                       33
0.5                                        26
0.25                                       24
1.25                                       18
0.75                                        3
NR                                          3
Unrated                                     3
4.125                                       2
2.8                                         2
3.1                                         2
2.9                                         2
1.1                                         2
4.25/5                                      2
0.1                                         1
3.65                                        1
3.7                                         1
3.4                                         1
3.6                                         1
3.2                                         1
2.3                                         1
2.125                                       1
2.85                                        1
3.5/2.5                                     1
3.125                                       1
0.9                                         1
2.1                                         1
2017-05-04 00:00:00                         1
5/2.5                                       1
4.5/5                                       1
2017-05-05 00:00:00                         1
2017-04-04 00:00:00                         1
NS                                          1
4.35                                        1
Detail of the lid (click to enlarge).       1
1.8                                         1
Name: count, dtype: int64

In [10]:
#convert column Stars to numeric
df['Stars']=pd.to_numeric(df['Stars'], errors='coerce')
df['Stars'].value_counts()

Stars
5.000    938
3.500    678
3.750    643
4.000    541
4.500    315
3.250    250
4.250    240
3.000    208
2.750    124
2.000    124
2.500    117
4.750    113
1.500     64
0.000     61
1.000     53
1.750     35
2.250     33
0.500     26
0.250     24
1.250     18
0.750      3
3.100      2
4.125      2
2.900      2
1.100      2
2.800      2
4.350      1
3.400      1
3.650      1
3.200      1
2.300      1
2.850      1
3.600      1
0.100      1
3.700      1
2.125      1
3.125      1
0.900      1
2.100      1
1.800      1
Name: count, dtype: int64

In [11]:
#remove all Nah
df = df.dropna()
df.isnull().sum()

Brand      0
Variety    0
Style      0
Country    0
Stars      0
dtype: int64

In [12]:
#test df
df

,Brand,Variety,Style,Country,Stars
0,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5.0
1,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5.0
2,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5
3,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5
4,Samyang Foods,Samyand Ramen,Pack,United States,5.0
...,...,...,...,...,...
4645,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
4646,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.0
4647,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.0
4648,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.0
4649,Westbrae,Miso Ramen,Pack,United States,0.5

In [13]:
#convert dataframe to csv
df.to_csv('ramen_rating_2023_clean.csv', index=None)

In [14]:
pd.read_csv("ramen_rating_2023_clean.csv")

,Brand,Variety,Style,Country,Stars
0,Jasmine,XXL Bihun Segera Penang White Curry,Pack,Malaysia,5.0
1,Indomie,Mi Instan Mi Keriting Goreng Spesial,Pack,Indonesia,5.0
2,MAMA,Oriental Kitchen Dried Instant Noodles Truffle...,Pack,Thailand,4.5
3,Ottogi,Jin Jjajang Smoked Black Bean Flavor,Pack,United States,4.5
4,Samyang Foods,Samyand Ramen,Pack,United States,5.0
...,...,...,...,...,...
4627,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5
4628,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1.0
4629,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2.0
4630,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2.0
4631,Westbrae,Miso Ramen,Pack,United States,0.5